import logging
from typing import Dict, Optional, List
from conversation_manager import ConversationManager

logger = logging.getLogger(__name__)

class ConstraintAwareQueryGenerator:
    """Generates SQL queries while respecting user constraints and conversation context"""
    
    def __init__(self, conversation_manager: ConversationManager):
        self.conversation_manager = conversation_manager
        
    def generate_query(self, user_request: str, schema: Dict, llm_generated_query: str) -> str:
        """
        Validate and modify LLM-generated query based on user constraints
        
        Args:
            user_request: The user's natural language request
            schema: Database schema information
            llm_generated_query: The query generated by LLM
            
        Returns:
            Modified query that respects user constraints
        """
        constraints = self.conversation_manager.get_active_constraints()
        modified_query = llm_generated_query
        
        # Check for JOIN constraint violation
        if constraints.get("no_joins", False):
            if self._has_join(modified_query):
                logger.warning("LLM query contains JOIN but user requested no joins. Rewriting...")
                modified_query = self._remove_joins(modified_query, constraints, schema)
        
        # Check for specific table constraint
        target_table = constraints.get("target_table")
        if target_table:
            if not self._uses_table(modified_query, target_table):
                logger.warning(f"LLM query doesn't use target table {target_table}. Rewriting...")
                modified_query = self._rewrite_for_table(modified_query, target_table, constraints, schema)
        
        # Log the modification
        if modified_query != llm_generated_query:
            logger.info(f"Query modified to respect constraints:\nOriginal: {llm_generated_query}\nModified: {modified_query}")
            
        return modified_query
    
    def _has_join(self, query: str) -> bool:
        """Check if query contains JOIN operations"""
        query_upper = query.upper()
        join_keywords = ["JOIN", "INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "OUTER JOIN", "CROSS JOIN"]
        return any(keyword in query_upper for keyword in join_keywords)
    
    def _uses_table(self, query: str, table_name: str) -> bool:
        """Check if query uses specific table"""
        query_upper = query.upper()
        table_upper = table_name.upper()
        return table_upper in query_upper
    
    def _remove_joins(self, query: str, constraints: Dict, schema: Dict) -> str:
        """Remove joins and rewrite query for single table"""
        target_table = constraints.get("target_table", "oee_details_data")
        operation = constraints.get("operation", "count_distinct")
        target_column = constraints.get("target_column", "machine_id")
        
        # Simple rewrite based on operation type
        if operation == "count_distinct":
            # Find the column name that matches target
            column_name = self._find_column_name(target_column, target_table, schema)
            return f"SELECT COUNT(DISTINCT {column_name}) FROM {target_table}"
        
        # Default: select all from target table
        return f"SELECT * FROM {target_table} LIMIT 100"
    
    def _rewrite_for_table(self, query: str, target_table: str, constraints: Dict, schema: Dict) -> str:
        """Rewrite query to use specific table"""
        operation = constraints.get("operation", "count_distinct")
        target_column = constraints.get("target_column", "machine_id")
        
        if operation == "count_distinct":
            column_name = self._find_column_name(target_column, target_table, schema)
            return f"SELECT COUNT(DISTINCT {column_name}) FROM {target_table}"
        
        return f"SELECT * FROM {target_table} LIMIT 100"
    
    def _find_column_name(self, target_column: str, table_name: str, schema: Dict) -> str:
        """
        Find the actual column name in the table that matches the target.
        Queries the active schema to ensure the returned column actually exists.
        """
        tables = schema.get("tables", [])
        columns = []
        for t in tables:
            if t.get("name") == table_name:
                columns = [c.get("name") for c in t.get("columns", [])]
                break
                
        if not columns:
            return "id"
            
        # 1. Exact match
        if target_column in columns:
            return target_column
            
        # 2. Check if target_column is in any column name
        for col in columns:
            if target_column.lower() in col.lower():
                return col
                
        # 3. Fuzzy match / common patterns
        common_patterns = [
            "machine_id",
            "loop_id",
            "variant",
            "grammage",
            "timestamp",
            "start_time"
        ]
        for pat in common_patterns:
            if pat in columns:
                return pat
                
        # 4. Fallback to 'id' or first column if exists
        if "id" in columns:
            return "id"
        return columns[0] if columns else "id"
    
    def build_context_prompt(self, user_request: str, schema: Dict) -> str:
        """Build enhanced prompt with conversation context for LLM"""
        from pathlib import Path
        
        context = self.conversation_manager.get_conversation_context(last_n=5)
        constraints = self.conversation_manager.get_active_constraints()
        
        rules = []
        if constraints.get("no_joins", False):
            rules.append("- DO NOT USE ANY JOIN OPERATIONS")
            rules.append("- Query must use only a single table")
        
        if constraints.get("target_table"):
            rules.append(f"- Query MUST use table: {constraints['target_table']}")
        
        if constraints.get("operation") == "count_distinct":
            rules.append("- Use COUNT(DISTINCT column_name) for counting unique values")
            
        rules_str = "\n".join(rules) if rules else "No active strict constraints."
        
        try:
            prompt_path = Path(__file__).parent / "prompts" / "constraint_generator.txt"
            template = prompt_path.read_text(encoding="utf-8")
            return template.format(
                context=context,
                constraint_rules=rules_str,
                user_request=user_request
            )
        except Exception as e:
            logger.error(f"Failed to load constraint_generator prompt: {e}")
            # Fallback inline prompt if file is missing
            return f"Generate SQL for {user_request}. Constraints: {rules_str}"
