import re
import json
import logging
import asyncio
from pathlib import Path
from litellm import acompletion
from backend.config import settings

logger = logging.getLogger(__name__)

# Dynamically load LLM prompts from dedicated files
PROMPTS_DIR = Path(__file__).parent / "prompts"

def load_prompt(filename: str) -> str:
    path = PROMPTS_DIR / filename
    try:
        return path.read_text(encoding="utf-8").strip()
    except Exception as e:
        logger.error(f"Failed to load prompt file {path}: {e}")
        # Fallback in case of a file read emergency
        return ""

SQL_SYSTEM_PROMPT = load_prompt("sql_system.txt")
EXPLAINER_PROMPT = load_prompt("explainer.txt")

def reload_prompts():
    global SQL_SYSTEM_PROMPT, EXPLAINER_PROMPT
    SQL_SYSTEM_PROMPT = load_prompt("sql_system.txt")
    EXPLAINER_PROMPT = load_prompt("explainer.txt")
    logger.info("AI System Prompts reloaded dynamically from disk.")

class SQLGenerator:
    def __init__(self, db_connector):
        self.db = db_connector

    def _format_schema(self, schema_info: dict) -> str:
        lines = []
        for table in schema_info.get("tables", []):
            row_count = table.get("row_count", 0)
            status = f"({row_count:,} rows)" if row_count > 0 else "(0 rows - EMPTY)"
            lines.append(f"Table: {table['name']} {status}")
            cols = [f"{c['name']} ({c['type']})" for c in table.get("columns", [])]
            lines.append("  Columns: " + ", ".join(cols))
            # Include sample rows for better LLM context
            if table.get("samples"):
                lines.append(f"  Sample row: {table['samples'][0]}")
        return "\n".join(lines)
    
    async def generate_sql(self, query: str, schema_info: dict, domain_hints: str, max_retries: int = 1, matched_tables: list = None) -> str:
        if matched_tables:
            domain_hints = f"{domain_hints}\n\nCONFIRMED RELEVANT TABLES TO USE: {', '.join(matched_tables)}"
        schema_text = self._format_schema(schema_info)
        prompt = SQL_SYSTEM_PROMPT.format(schema_text=schema_text, domain_hints=domain_hints)
        
        # Explicitly print and log enhanced_hints (domain_hints) and the full system prompt
        print("\n" + "=" * 60)
        print("💡 [FORMULA & DOMAIN HINTS REACHING LLM] 💡")
        print(domain_hints)
        print("-" * 60)
        print("🔥 [FULL SQL GENERATOR SYSTEM PROMPT] 🔥")
        print(prompt)
        print("=" * 60 + "\n")
        
        logger.info(f"Domain hints reaching LLM:\n{domain_hints}")
        logger.info(f"Generating SQL for query: '{query}'")
        logger.info(f"Full System Prompt sent to LLM:\n{prompt}")
        
        last_error = None
        last_sql = None
        
        for attempt in range(max_retries + 1):
            messages = [
                {"role": "system", "content": prompt},
                {"role": "user", "content": query}
            ]
            
            # Add self-correction context if previous attempt failed
            if last_error and last_sql:
                messages.append({"role": "assistant", "content": last_sql})
                messages.append({
                    "role": "user", 
                    "content": f"That SQL failed with error: {last_error}. Fix it and return ONLY the corrected SQL. DO NOT include any explanations, introduction, markdown code blocks, or conversational text. Start directly with SELECT."
                })
                logger.info(f"Retry attempt {attempt} with self-correction")
            
            try:
                response = await acompletion(
                    model=f"{settings.LLM_PROVIDER}/{settings.LLM_MODEL}",
                    messages=messages,
                    api_base=settings.OLLAMA_BASE_URL if settings.LLM_PROVIDER == "ollama" else None,
                    temperature=0.0,
                    timeout=120
                )
                sql = response.choices[0].message.content.strip()
                
                # Clean up potential markdown formatting blocks generated by the LLM
                sql_blocks = re.findall(r"```sql\s*(.*?)\s*```", sql, flags=re.DOTALL | re.IGNORECASE)
                if not sql_blocks:
                    sql_blocks = re.findall(r"```\s*(.*?)\s*```", sql, flags=re.DOTALL | re.IGNORECASE)
                
                if sql_blocks:
                    # Robust extraction: the last block is typically the final corrected SQL candidate
                    sql = sql_blocks[-1].strip()
                else:
                    # No closed code blocks found. Let's see if there is an unclosed code block.
                    # An unclosed block starts with ```sql or ``` and doesn't have a closing ```
                    last_start = -1
                    marker_len = 0
                    for marker in ["```sql", "```SQL", "```"]:
                        idx = sql.rfind(marker)
                        if idx > last_start:
                            last_start = idx
                            marker_len = len(marker)
                    
                    if last_start != -1:
                        # Extract everything after the last code block start marker
                        sql = sql[last_start + marker_len:].strip()
                        # If there is a trailing unclosed marker at the end, remove it
                        sql = re.sub(r"\s*```$", "", sql, flags=re.IGNORECASE)
                    else:
                        # If there are no markdown blocks at all, see if the text contains a SELECT statement
                        select_match = re.search(r"\bSELECT\b", sql, flags=re.IGNORECASE)
                        if select_match:
                            sql = sql[select_match.start():].strip()
                        else:
                            # Strip any leading ```sql or similar in case they are at the very beginning
                            sql = re.sub(r"^```sql\s*", "", sql, flags=re.IGNORECASE)
                            sql = re.sub(r"^```\s*", "", sql, flags=re.IGNORECASE)
                            sql = re.sub(r"\s*```$", "", sql, flags=re.IGNORECASE)
                
                # Trim semicolons and whitespaces
                sql = sql.strip().rstrip(";")
                
                # Validate SQL with EXPLAIN dry-run before returning
                try:
                    await self.db.execute_query(f"EXPLAIN {sql}")
                    logger.info(f"Generated and validated SQL: {sql}")
                    return sql
                except Exception as validation_error:
                    last_error = str(validation_error)
                    last_sql = sql
                    logger.warning(f"SQL validation failed (attempt {attempt + 1}): {validation_error}")
                    
                    # If this was the last retry, raise the error
                    if attempt == max_retries:
                        raise validation_error
                    
            except Exception as e:
                if attempt == max_retries:
                    logger.error(f"SQL Generation failed after {max_retries + 1} attempts: {e}")
                    raise e
                last_error = str(e)
        
        raise Exception(f"SQL generation failed after {max_retries + 1} attempts")

    async def explain_results(self, query: str, sql: str, results: dict, extra_context: str = "") -> str:
        try:
            sample_results = json.dumps(results.get("rows", [])[:20], indent=2)
        except Exception as e:
            logger.error(f"Error serializing results: {e}")
            sample_results = str(results.get("rows", []))
        
        row_count = results.get("row_count", 0)
        
        is_count_query = False
        if row_count == 1 and results.get("rows"):
            try:
                row_data = results["rows"][0]
                if isinstance(row_data, dict) and len(row_data) == 1:
                    key = list(row_data.keys())[0]
                    if key.lower() in ["count", "total", "count(*)"]:
                        is_count_query = True
            except Exception:
                pass
        
        empty_result_guidance = ""
        if row_count == 0 or (is_count_query and results.get("rows") and len(results["rows"]) > 0):
            try:
                if is_count_query:
                    count_value = list(results["rows"][0].values())[0]
                    if count_value == 0:
                        empty_result_guidance = """\n\nIMPORTANT: The result is empty or zero. You MUST:
1. Clearly state what was found (or not found)
2. Provide 2-3 possible reasons why this might be the case
3. Suggest alternative tables or approaches the user could try
4. Ask helpful follow-up questions to guide the user

Example format:
"Based on the query results, there are 0 [items] in the [table] table. This could mean:
- Possibility 1: [reason]
- Possibility 2: [reason]
- Possibility 3: [reason]

To investigate further, you might want to:
- Check [alternative table/approach]
- Verify [data condition]

Would you like me to check [specific suggestion]?"
"""
            except Exception:
                pass
        
        prompt = EXPLAINER_PROMPT.format(
            query=query,
            sql=sql,
            columns=results.get("columns", []),
            row_count=row_count,
            sample_results=sample_results
        ) + empty_result_guidance
        
        if extra_context:
            prompt = f"ADDITIONAL CONTEXT FROM RAG DOCUMENTS:\n{extra_context}\n\n---\n\n{prompt}"
        
        logger.info(f"Explaining results for query: '{query}'")
        try:
            response = await acompletion(
                model=f"{settings.LLM_PROVIDER}/{settings.LLM_MODEL}",
                messages=[
                    {"role": "user", "content": prompt}
                ],
                api_base=settings.OLLAMA_BASE_URL if settings.LLM_PROVIDER == "ollama" else None,
                temperature=0.3,  # Slightly higher for more creative suggestions
                timeout=120
            )
            explanation = response.choices[0].message.content.strip()
            return explanation
        except Exception as e:
            logger.error(f"Explanation generation failed: {e}")
            raise e

    async def explain_rag_concept(self, query: str, rag_context: str) -> str:
        """
        Explain a conceptual manufacturing question directly using RAG reference documents.
        """
        prompt = f"""You are an expert industrial manufacturing assistant. 
Explain the following manufacturing concept or term to the user.

User Question: {query}

Retrieved Reference Material:
{rag_context if rag_context else 'No reference material found.'}

Instructions:
1. Be clear, precise, and professional.
2. Directly answer the question using the retrieved reference material.
3. If the reference material doesn't contain the answer, use your general knowledge of potato chip manufacturing and smart factory systems to provide a helpful, accurate definition.

Answer:"""
        logger.info(f"Explaining RAG concept for query: '{query}'")
        try:
            response = await acompletion(
                model=f"{settings.LLM_PROVIDER}/{settings.LLM_MODEL}",
                messages=[{"role": "user", "content": prompt}],
                api_base=settings.OLLAMA_BASE_URL if settings.LLM_PROVIDER == "ollama" else None,
                temperature=0.3,
                timeout=120
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            logger.error(f"RAG Explanation generation failed: {e}")
            raise e

    async def explain_error_conversational(self, query: str, error_msg: str, stage: str) -> str:
        """
        Explain a SQL generator or database execution error to the user in a friendly,
        plain-English way, and ask a clarifying question so the user can understand and help us fix it.
        """
        prompt = f"""You are a friendly and expert industrial database analyst assistant.
The user asked a question: "{query}"

However, we encountered a technical issue during the {stage} stage.
Technical Issue: "{error_msg}"

Instructions:
1. Translate this technical issue into a warm, friendly, plain English response that an ordinary factory manager can understand.
2. DO NOT mention database tables, columns, rows, SQL, code, or technical variables. Speak purely in terms of business concepts (OEE, wastage, silos, feeders, client orders, etc.).
3. Explain simply what went wrong (e.g., if a column or relation didn't exist, explain that we couldn't match or find records for that specific combination or aspect of data).
4. Ask a polite, business-oriented clarifying question to help us get the correct information (e.g., "Could you please clarify what specific metric or machine you would like to analyze?").
5. Keep your response extremely brief, polite, and under 50 words.
6. DO NOT include any introductory preamble, conversational filler, or introductory phrase. Output ONLY the plain English explanation directly. Do NOT wrap it in quotes. Do NOT start with "Here's a friendly explanation of the technical issue" or any similar phrase. Start directly with the business explanation.

Response:"""
        logger.info(f"Explaining database error conversationally for query: '{query}'")
        try:
            response = await acompletion(
                model=f"{settings.LLM_PROVIDER}/{settings.LLM_MODEL}",
                messages=[{"role": "user", "content": prompt}],
                api_base=settings.OLLAMA_BASE_URL if settings.LLM_PROVIDER == "ollama" else None,
                temperature=0.3,
                timeout=120
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            logger.error(f"Error explanation generation failed: {e}")
            raise e

