import re
import json
import logging
import asyncio
from pathlib import Path
from litellm import acompletion
from backend.config import settings

logger = logging.getLogger(__name__)

# Dynamically load LLM prompts from dedicated files
PROMPTS_DIR = Path(__file__).parent / "prompts"

def load_prompt(filename: str) -> str:
    path = PROMPTS_DIR / filename
    try:
        return path.read_text(encoding="utf-8").strip()
    except Exception as e:
        logger.error(f"Failed to load prompt file {path}: {e}")
        # Fallback in case of a file read emergency
        return ""

SQL_SYSTEM_PROMPT = load_prompt("sql_system.txt")
EXPLAINER_PROMPT = load_prompt("explainer.txt")

class SQLGenerator:
    def __init__(self, db_connector):
        self.db = db_connector

    def _format_schema(self, schema_info: dict) -> str:
        lines = []
        for table in schema_info.get("tables", []):
            lines.append(f"Table: {table['name']}")
            cols = [f"{c['name']} ({c['type']})" for c in table.get("columns", [])]
            lines.append("  Columns: " + ", ".join(cols))
            # Include sample rows for better LLM context
            if table.get("samples"):
                lines.append(f"  Sample row: {table['samples'][0]}")
        return "\n".join(lines)

    async def generate_sql(self, query: str, schema_info: dict, domain_hints: str, max_retries: int = 2) -> str:
        schema_text = self._format_schema(schema_info)
        prompt = SQL_SYSTEM_PROMPT.format(schema_text=schema_text, domain_hints=domain_hints)
        
        logger.info(f"Generating SQL for query: '{query}'")
        
        last_error = None
        last_sql = None
        
        for attempt in range(max_retries + 1):
            messages = [
                {"role": "system", "content": prompt},
                {"role": "user", "content": query}
            ]
            
            # Add self-correction context if previous attempt failed
            if last_error and last_sql:
                messages.append({"role": "assistant", "content": last_sql})
                messages.append({
                    "role": "user", 
                    "content": f"That SQL failed with error: {last_error}. Fix it and return only the corrected SQL."
                })
                logger.info(f"Retry attempt {attempt} with self-correction")
            
            try:
                response = await acompletion(
                    model=f"{settings.LLM_PROVIDER}/{settings.LLM_MODEL}",
                    messages=messages,
                    api_base=settings.OLLAMA_BASE_URL if settings.LLM_PROVIDER == "ollama" else None,
                    temperature=0.0,
                    timeout=120
                )
                sql = response.choices[0].message.content.strip()
                
                # Clean up potential markdown formatting blocks generated by the LLM
                sql = re.sub(r"^```sql\s*", "", sql, flags=re.IGNORECASE)
                sql = re.sub(r"^```\s*", "", sql, flags=re.IGNORECASE)
                sql = re.sub(r"\s*```$", "", sql, flags=re.IGNORECASE)
                
                # Trim semicolons and whitespaces
                sql = sql.strip().rstrip(";")
                
                # Validate SQL with EXPLAIN dry-run before returning
                try:
                    await self.db.execute_query(f"EXPLAIN {sql}")
                    logger.info(f"Generated and validated SQL: {sql}")
                    return sql
                except Exception as validation_error:
                    last_error = str(validation_error)
                    last_sql = sql
                    logger.warning(f"SQL validation failed (attempt {attempt + 1}): {validation_error}")
                    
                    # If this was the last retry, raise the error
                    if attempt == max_retries:
                        raise validation_error
                    
            except Exception as e:
                if attempt == max_retries:
                    logger.error(f"SQL Generation failed after {max_retries + 1} attempts: {e}")
                    raise e
                last_error = str(e)
        
        raise Exception(f"SQL generation failed after {max_retries + 1} attempts")

    async def explain_results(self, query: str, sql: str, results: dict, extra_context: str = "") -> str:
        sample_results = json.dumps(results.get("rows", [])[:20], indent=2)
        prompt = EXPLAINER_PROMPT.format(
            query=query,
            sql=sql,
            columns=results.get("columns", []),
            row_count=results.get("row_count", 0),
            sample_results=sample_results
        )
        if extra_context:
            prompt = f"ADDITIONAL CONTEXT FROM RAG DOCUMENTS:\n{extra_context}\n\n---\n\n{prompt}"
        
        logger.info(f"Explaining results for query: '{query}'")
        try:
            response = await acompletion(
                model=f"{settings.LLM_PROVIDER}/{settings.LLM_MODEL}",
                messages=[
                    {"role": "user", "content": prompt}
                ],
                api_base=settings.OLLAMA_BASE_URL if settings.LLM_PROVIDER == "ollama" else None,
                temperature=0.2,
                timeout=120
            )
            explanation = response.choices[0].message.content.strip()
            return explanation
        except Exception as e:
            logger.error(f"Explanation generation failed: {e}")
            raise e
